package com.example.demo.BookDetails;


import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.bookSearch.book;

@RestController
@Controller // This means that this class is a Controller
public class authorContorller {

	@Autowired // This means to get the bean called BooksRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private authorRespository austhorRepository;

	@RequestMapping(value = "/Author", method = RequestMethod.POST)
    public String  newEmployee(String des) {
		
		author author = new author("TEST AUTHOR",des,"publisher");
	
		austhorRepository.save(author);
         return "new author";

    }
	
	@GetMapping(path = "/Author/all")
	public @ResponseBody List<Author> getBooks() {
		return AuthorRepository.findAll();

	}

}