package com.example.demo.bookSearch;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Controller // This means that this class is a Controller
public class bookController {

	@Autowired // This means to get the bean called BooksRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private bookRespository BooksRepository;

	@GetMapping(path = "/search/top10")
	public @ResponseBody Iterable<book> getAllBookss() {
// This returns a JSON or XML with the Bookss
		List<book> list = BooksRepository.findAll();
		List<book> books = new ArrayList<>();

		for (int i = 0; i < list.size(); i++) {
			list.get(i).getCopiessold();
			if (books.size() < 10) {

				books.add(list.get(i));

			} else if (books.size() == 10) {

				sort(books);
			}
			if(books.size() == 10) {
				if(list.get(i).getCopiessold() > books.get(books.size()-1).getCopiessold()) {
					books.set(books.size()-1, list.get(i));

				}
			}

		}
		sort(books);
		Iterable<book> rbooks = books;
		return rbooks;
	}

	private void sort(List<book> books) {
		for (int x = 0; x < 10; x++) {
			for (int c = x; c < 10; c++) {
				if (books.get(x).getCopiessold() < books.get(c).getCopiessold()) {

					book bookTemp = books.get(x);
					books.set(x, books.get(c));
					books.set(c, bookTemp);
				}
			}
		}


	}

	@GetMapping(path = "/HelloWorld")
	public String HelloWorld() {
		return "Hello World";
	}

	@GetMapping(path = "/search/genre")
	public ResponseEntity<List<book>> getBooksByName(@RequestParam String genre) {
		return new ResponseEntity<>(BooksRepository.findBygenreIgnoreCase(genre), HttpStatus.OK);

	}

	@GetMapping(path = "/search/ISBN")
	public ResponseEntity<List<book>> findByisbn(@RequestParam Integer ISBN) {
		return new ResponseEntity<>(BooksRepository.findByISBN(ISBN), HttpStatus.OK);

	}
	
	@GetMapping(path = "/search/AllBooks")
	public @ResponseBody Iterable<book> getBooks() {
		return BooksRepository.findAll();

	}

	@GetMapping(path = "/search/author")
	public ResponseEntity<List<book>> getBooksByauthor(@RequestParam String author) {
		return new ResponseEntity<>(BooksRepository.findByauthor(author), HttpStatus.OK);

	}
	
	

}